"""The year-end pack's cover names the PRACTICE, and never this product.

── THE DEFECT ───────────────────────────────────────────────────────────────
The cover of a set of financial statements a CA signs and hands to their client
read

    Prepared by:   PracticeSync AI — Practice Management Platform

and the footer under the last schedule said "Generated by PracticeSync AI on
…". The software did not prepare them; the practice did, and a reader of a
signed set asks who stands behind it.

── WHY IT SURVIVED ──────────────────────────────────────────────────────────
The PDF service is handed an ENGAGEMENT, and `year_end_engagements` carries
`firm_id` and no name. There was nothing to print, so a literal went in.

── THE THREE RULES ──────────────────────────────────────────────────────────
**ONE RESOLVER FOR THREE EXPORTS.** `routers/year_end_exports._with_firm_name`
fetches once and all six call sites go through it, so the name cannot be
threaded into two endpoints and forgotten in the third — which is exactly how
half a fix ships.

**A FAILED FETCH IS NOT A FAILED EXPORT.** `domain/firm/letterhead` answers
"The practice" where no name is known. Vague and true beats refusing to produce
a CA's year-end pack because a name lookup timed out — and beats falling back
to the product's name, which is the defect being closed.

**AND NOTHING HERE REACHES THE CLIENT'S OWN DOCUMENTS.** CLAUDE.md records
three separately-fixed bugs where the practice's logo, signature placement or
UPI id reached a sales invoice, a payslip or a customer statement — documents
the CLIENT issues to a stranger. This is the pack the PRACTICE issues.
"""
from __future__ import annotations

import pathlib
import re

API = pathlib.Path(__file__).resolve().parents[1]


def _code(rel: str) -> str:
    s = (API / rel).read_text()
    s = re.sub(r'"""[\s\S]*?"""', "", s)
    return re.sub(r"^\s*#.*$", "", s, flags=re.M)


def test_the_pack_does_not_name_this_product():
    src = _code("services/year_end_pdf_service.py")
    assert "PracticeSync" not in src, (
        "the year-end pack names the software on a document a CA signs")


def test_the_cover_and_the_footer_both_ask_the_letterhead():
    src = _code("services/year_end_pdf_service.py")
    assert "prepared_by(" in src, "the cover must ask domain/firm/letterhead"
    assert "generated_note(" in src, "and so must the footer"


def test_every_export_resolves_the_name_through_one_helper():
    """Counted, not spot-checked. Three endpoints × two branches (mock and
    live) is six call sites, and a fix applied to five of six is the shape this
    asserts against."""
    src = _code("routers/year_end_exports.py")
    builders = re.findall(
        r"generate_(?:financial_statements|notes|complete_pack)_pdf\(\s*([A-Za-z_][\w.]*)", src)
    assert len(builders) >= 6, f"only {len(builders)} PDF builds found — the file moved"
    bare = [b for b in builders if b != "_with_firm_name"]
    assert not bare, (
        f"{len(bare)} export(s) build a PDF from the raw engagement, so their "
        "cover falls back to 'The practice' while the others name the firm")


def test_the_fallback_is_the_role_and_never_the_product():
    import sys
    sys.path.insert(0, str(API))
    from domain.firm.letterhead import (UNNAMED_PRACTICE, firm_name_of,
                                        generated_note, prepared_by)

    assert "PracticeSync" not in UNNAMED_PRACTICE
    assert prepared_by("Sharma & Co") == "Sharma & Co"
    # A name of spaces is not a name — it would print as an empty cell beside
    # the label, which reads as a document that forgot to say.
    assert prepared_by("   ") == UNNAMED_PRACTICE
    assert prepared_by(None) == UNNAMED_PRACTICE
    assert firm_name_of({"name": "  A  "}) == "A"
    assert firm_name_of({"name": "   "}) is None
    assert firm_name_of(None) is None
    assert firm_name_of({"name": 7}) is None
    assert "PracticeSync" not in generated_note(None, "01 Apr 2027 01:00 IST")
    assert "Sharma & Co" in generated_note("Sharma & Co", "x")


def test_the_clients_own_documents_stay_free_of_the_practice():
    """The three CLAUDE.md records this rule for. A letterhead import in any of
    them is the bug being re-introduced from the other direction."""
    for name in ("invoice_pdf_service.py", "payslip_pdf_service.py",
                 "statement_pdf_service.py"):
        assert "letterhead" not in _code(f"services/{name}"), (
            f"{name} produces a document the CLIENT issues to a stranger; the "
            "practice's name does not belong on it")
