"""
E-Invoice Integration — IRN generation, cancellation, status.
CGST Act Section 31B, Rule 48(4) — E-Invoice mandate.

# CA REVIEW REQUIRED — DO NOT AUTO-SUBMIT to IRP
"""
from __future__ import annotations
import logging
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field, field_validator
from core.permissions import rbac
from models.common import api_response
from services.timeline_service import timeline_service

router = APIRouter(prefix="/api/einvoice", tags=["einvoice"])
_logger = logging.getLogger("caflow.einvoice.router")


_GST_TREATMENTS = {
    "regular", "export_with_payment", "export_without_payment",
    "sez_with_payment", "sez_without_payment", "deemed_export",
}


class CreateEInvoiceRequest(BaseModel):
    client_id: str
    invoice_number: str
    invoice_date: str  # YYYY-MM-DD
    sales_invoice_id: Optional[str] = None
    provider: str = "manual"
    # Compliance treatment captured for the IRN (metadata only — never used in
    # any tax/journal computation). LUT/Bond ref applies to without-payment.
    gst_treatment: Optional[str] = None
    lut_number: Optional[str] = None

    @field_validator("gst_treatment")
    @classmethod
    def _valid_treatment(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v not in _GST_TREATMENTS:
            raise ValueError(f"Invalid gst_treatment '{v}'.")
        return v


class RecordIRNRequest(BaseModel):
    irn: str
    ack_number: str
    ack_date: str
    qr_data: Optional[str] = None
    provider_response: Optional[dict] = None


class CancelIRNRequest(BaseModel):
    cancellation_reason: str


@router.post("/records")
def create_record(
    req: CreateEInvoiceRequest,
    current_user: dict = Depends(rbac("gst", "compute")),
):
    """Create e-invoice record in draft state."""
    from domain.income_tax.einvoice_service import create_einvoice_record
    try:
        rec = create_einvoice_record(
            firm_id=current_user["firm_id"],
            client_id=req.client_id,
            invoice_number=req.invoice_number,
            invoice_date=req.invoice_date,
            created_by=current_user["id"],
            sales_invoice_id=req.sales_invoice_id,
            provider=req.provider,
            gst_treatment=req.gst_treatment,
            lut_number=req.lut_number,
        )
        return api_response(True, {**rec, "ca_review_required": True})
    except Exception as e:
        raise HTTPException(500, detail=str(e))


@router.get("/records")
def list_records(
    client_id: str,
    status: Optional[str] = None,
    current_user: dict = Depends(rbac("gst", "read")),
):
    from domain.income_tax.einvoice_service import list_einvoices
    return api_response(True, list_einvoices(current_user["firm_id"], client_id, status))


@router.post("/records/{record_id}/irn-generated")
def record_irn_generated(
    record_id: str,
    req: RecordIRNRequest,
    current_user: dict = Depends(rbac("gst", "approve")),
):
    """
    Record IRN generated by CA on IRP portal.
    # CA REVIEW REQUIRED — CA must generate IRN manually on https://einvoice1.gst.gov.in
    """
    from domain.income_tax.einvoice_service import record_irn_generated as _record
    try:
        result = _record(
            firm_id=current_user["firm_id"],
            record_id=record_id,
            irn=req.irn,
            ack_number=req.ack_number,
            ack_date=req.ack_date,
            qr_data=req.qr_data,
            provider_response=req.provider_response,
        )
        # Bug fix (Batch 7): timeline_service.log takes title/entity_*, not
        # action/metadata — the old call raised TypeError → 500. Scoping to the
        # sales invoice also surfaces the event in the invoice Hub timeline.
        timeline_service.log(
            client_id=result.get("client_id", ""),
            firm_id=current_user["firm_id"],
            category="tax",
            title="E-Invoice IRN generated",
            description=f"IRN {req.irn} (ACK {req.ack_number})",
            severity="success",
            entity_type="sales_invoice",
            entity_id=result.get("sales_invoice_id"),
        )
        return api_response(True, result)
    except Exception as e:
        raise HTTPException(500, detail=str(e))


@router.post("/records/{record_id}/cancel")
def cancel_irn(
    record_id: str,
    req: CancelIRNRequest,
    current_user: dict = Depends(rbac("gst", "approve")),
):
    """
    Record IRN cancellation.
    # CA REVIEW REQUIRED — Cancellation must be done on IRP portal first
    """
    from domain.income_tax.einvoice_service import record_irn_cancelled
    try:
        result = record_irn_cancelled(
            firm_id=current_user["firm_id"],
            record_id=record_id,
            cancellation_reason=req.cancellation_reason,
        )
        timeline_service.log(
            client_id=result.get("client_id", ""),
            firm_id=current_user["firm_id"],
            category="tax",
            title="E-Invoice cancelled",
            description=f"IRN cancelled: {req.cancellation_reason}",
            severity="warning",
            entity_type="sales_invoice",
            entity_id=result.get("sales_invoice_id"),
        )
        return api_response(True, result)
    except Exception as e:
        raise HTTPException(500, detail=str(e))
