-- Migration 124: Atomic invoice number sequence + UNIQUE constraint
--
-- Problem 1: generate_next_invoice_number() calls the RPC `next_invoice_number`.
-- This migration defines that function (and its backing per-firm counter table)
-- so invoice creation never 500s.
--
-- Problem 2: fee_invoices.invoice_no had no UNIQUE constraint, so concurrent
-- requests could theoretically produce duplicate invoice numbers.
--
-- Fix: an atomic sequence function backed by a per-firm counter table
-- (INSERT ... ON CONFLICT DO UPDATE is a single atomic statement in Postgres),
-- then UNIQUE(firm_id, invoice_no) to enforce uniqueness at the DB level.
--
-- The counter column is `last_number` to match the column already present in
-- deployed environments. CREATE OR REPLACE keeps the function in sync (adds
-- SECURITY DEFINER + a fixed search_path so it runs regardless of caller RLS
-- and is not flagged by the function_search_path_mutable advisor).
-- Fully idempotent.

-- ── Per-firm counter table ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.invoice_sequences (
    firm_id     UUID        NOT NULL PRIMARY KEY REFERENCES public.firms(id) ON DELETE CASCADE,
    last_number INTEGER     NOT NULL DEFAULT 0,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.invoice_sequences IS
  'Atomic per-firm invoice sequence counter. Mutated only via next_invoice_number().';

-- ── Atomic sequence function ──────────────────────────────────────────────────
-- Returns the next integer for the firm. INSERT on first call; atomic increment
-- on subsequent calls. Safe under concurrent requests — no TOCTOU window.
CREATE OR REPLACE FUNCTION public.next_invoice_number(p_firm_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_next INTEGER;
BEGIN
  INSERT INTO public.invoice_sequences (firm_id, last_number)
  VALUES (p_firm_id, 1)
  ON CONFLICT (firm_id) DO UPDATE
    SET last_number = invoice_sequences.last_number + 1,
        updated_at  = now()
  RETURNING last_number INTO v_next;
  RETURN v_next;
END;
$$;

COMMENT ON FUNCTION public.next_invoice_number(UUID) IS
  'Returns the next sequential invoice number for the given firm. Atomic — safe '
  'under concurrent requests. Called by invoice_repository.generate_next_invoice_number().';

-- ── UNIQUE constraint ─────────────────────────────────────────────────────────
-- Prevents duplicate invoice_no within a firm even under an unusual race.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fee_invoices_firm_invoice_no_unique'
      AND conrelid = 'public.fee_invoices'::regclass
  ) THEN
    ALTER TABLE public.fee_invoices
      ADD CONSTRAINT fee_invoices_firm_invoice_no_unique UNIQUE (firm_id, invoice_no);
  END IF;
END $$;

-- ── Execute privileges ────────────────────────────────────────────────────────
-- This is a SECURITY DEFINER function, so it must NOT be callable directly by
-- end users (an anon/authenticated caller could bump another firm's counter and
-- create invoice-number gaps). Invoice numbers are generated by the backend via
-- the service role only. Revoke from everyone else.
REVOKE EXECUTE ON FUNCTION public.next_invoice_number(UUID) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.next_invoice_number(UUID) FROM anon;
REVOKE EXECUTE ON FUNCTION public.next_invoice_number(UUID) FROM authenticated;
GRANT  EXECUTE ON FUNCTION public.next_invoice_number(UUID) TO service_role;
