-- Migration 167: numbered_document_atomic -- compensate the header/lines
-- insert gap in debit_notes and credit_notes (R3.11).
--
-- create_debit_note (routers/debit_notes.py) and create_credit_note
-- (routers/credit_notes.py) both insert a numbered header via
-- insert_with_number(), then insert the line rows as a SEPARATE,
-- unguarded call with no compensation -- if the lines insert fails, the
-- header (already committed) is left orphaned with zero lines. Same root
-- cause post_journal_atomic (migration 152) and settle_receipt_atomic
-- (migrations 160/162) already fixed for journals and receipts.
--
-- debit_note_lines and credit_note_lines share an identical column shape
-- (description/hsn_sac/quantity/rate_paise/gst_rate_bps/taxable_amount_paise/
-- cgst_paise/sgst_paise/igst_paise/line_total_paise, differing only in
-- their header FK column name) -- one shared function serves both,
-- parameterized by table/FK-column name, rather than duplicating the same
-- SQL twice.
--
-- Unlike post_journal_atomic (which treats a unique-number collision as an
-- idempotent retry and returns the existing winner), debit/credit note
-- numbers are generated by a COUNT-based sequence with no natural
-- idempotency key -- a collision here must retry with a FRESH number, not
-- return a stale winner. So this function does NOT catch unique_violation;
-- it lets it propagate so the caller's existing insert_with_number-style
-- Python retry loop (recomputing the sequence each attempt) can retry the
-- whole atomic call, header and lines together, exactly as before this
-- fix except now genuinely atomic per attempt.

CREATE OR REPLACE FUNCTION public.numbered_document_atomic(
  p_header_table text,
  p_header jsonb,
  p_lines_table text,
  p_lines jsonb,
  p_lines_fk_column text
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_keys text;
  v_row  RECORD;
BEGIN
  SELECT string_agg(quote_ident(k), ', ') INTO v_keys FROM jsonb_object_keys(p_header) AS k;
  IF v_keys IS NULL THEN
    RAISE EXCEPTION 'numbered_document_atomic: empty header payload';
  END IF;

  EXECUTE format(
    'INSERT INTO public.%1$I (%2$s) '
    'SELECT %2$s FROM jsonb_populate_record(NULL::public.%1$I, $1) '
    'RETURNING *',
    p_header_table, v_keys
  ) INTO v_row USING p_header;

  IF jsonb_array_length(p_lines) > 0 THEN
    EXECUTE format(
      'INSERT INTO public.%1$I ('
      '  %2$I, description, hsn_sac, quantity, rate_paise, gst_rate_bps, '
      '  taxable_amount_paise, cgst_paise, sgst_paise, igst_paise, line_total_paise'
      ') SELECT '
      '  $1, l->>''description'', l->>''hsn_sac'', '
      '  COALESCE((l->>''quantity'')::numeric, 1), '
      '  COALESCE((l->>''rate_paise'')::bigint, 0), '
      '  COALESCE((l->>''gst_rate_bps'')::int, 0), '
      '  COALESCE((l->>''taxable_amount_paise'')::bigint, 0), '
      '  COALESCE((l->>''cgst_paise'')::bigint, 0), '
      '  COALESCE((l->>''sgst_paise'')::bigint, 0), '
      '  COALESCE((l->>''igst_paise'')::bigint, 0), '
      '  COALESCE((l->>''line_total_paise'')::bigint, 0) '
      'FROM jsonb_array_elements($2) AS l',
      p_lines_table, p_lines_fk_column
    ) USING v_row.id, p_lines;
  END IF;

  RETURN to_jsonb(v_row);
END
$$;

GRANT EXECUTE ON FUNCTION public.numbered_document_atomic(text, jsonb, text, jsonb, text)
  TO authenticated, service_role;
