-- Migration 177 — E-Invoice GST treatment capture (Sales-Invoice Batch 7)
--
-- The e-invoice record is the correct home for the supply's GST treatment
-- (Export / SEZ / Deemed export, with or without payment) and the LUT/Bond
-- reference used for without-payment supplies. This is COMPLIANCE metadata on
-- the e-invoice record — it is NOT stored on the immutable sales invoice and
-- does NOT affect any journal or tax computation, so historical invoices and
-- the ledger are entirely unaffected.
--
-- Additive + nullable: existing rows default to NULL (a regular supply). The
-- create endpoint captures these when the CA prepares an IRN; the IRN itself is
-- still generated by the CA on the government portal and only recorded here
-- (# CA REVIEW REQUIRED — DO NOT AUTO-SUBMIT).

ALTER TABLE public.einvoice_records
  ADD COLUMN IF NOT EXISTS gst_treatment TEXT
    CHECK (gst_treatment IS NULL OR gst_treatment IN (
      'regular',
      'export_with_payment', 'export_without_payment',
      'sez_with_payment',    'sez_without_payment',
      'deemed_export'
    )),
  ADD COLUMN IF NOT EXISTS lut_number TEXT;
