/**
 * GST compensation cess on one line — the browser mirror of
 * `apps/api/domain/gst/compensation_cess.py`.
 *
 * Kept in its OWN module rather than added to `gstLine.ts` because cess is its
 * own levy: GST (Compensation to States) Act 2017 s.8, not CGST Act s.9. It is
 * charged on the same base as the three GST heads and then goes its own way —
 * s.11(2)'s proviso ring-fences the credit ("shall be utilised only towards
 * payment of cess"), so GSTR-3B's Table 6 set-off never sees it and neither
 * does `splitLineGst`'s return type.
 *
 * The other reason is mechanical: `shared/gst-parity-vectors.json` pins
 * `gstLine.splitLineGst` to the backend on exact strings, and `gstLine`'s
 * `ratePaiseFromRupees` is one of the four allowlisted `Math.round(x * 100)`
 * sites in the codebase. Widening that function's shape to carry a fourth head
 * would put a new computation inside the one pinned contract. This module has
 * its own vectors instead, generated by the same script.
 *
 * TWO LIMBS, ADDED. s.8(2) levies the cess "on the basis of VALUE, QUANTITY or
 * on such basis": aerated waters ad valorem, coal per tonne, cigarettes a
 * percentage PLUS a figure per thousand. A single percentage would silently
 * under-charge the last two.
 *
 * Both roundings match the server exactly: the ad valorem limb FLOORS with
 * integer division, as `_compute_line_gst` does, and the specific limb
 * TRUNCATES an exact decimal product, as `int(Decimal(str(qty)) * rate)` does.
 * BigInt throughout, for the same reason `gstLine.ts` uses it — integer floor
 * division is the one operation Python and JavaScript do identically.
 */

import { decimalTruncate, floorDivBigInt } from "./decimalMath.ts";

export interface LineCess {
  cess_paise: number;
  /** The s.8(2) "value" limb. */
  ad_valorem_paise: number;
  /** The s.8(2) "quantity" limb, per unit of THIS LINE'S OWN UQC. */
  specific_paise: number;
}

/**
 * The compensation cess on one line, in integer paise.
 *
 * `taxablePaise` is the value of supply AFTER a s.15(3)(a) discount — the same
 * base the GST heads use, because s.11(1) of the Compensation Act applies CGST
 * s.15 to this levy.
 *
 * Returns all-zero for a negative or non-finite input rather than throwing: a
 * preview must never blow up on a half-typed field, and the server refuses the
 * same inputs with a 422 when the form is submitted.
 */
export function lineCess(
  taxablePaise: number,
  quantity: number,
  cessRateBps?: number | null,
  cessSpecificPaisePerUnit?: number | null,
): LineCess {
  const NIL: LineCess = { cess_paise: 0, ad_valorem_paise: 0, specific_paise: 0 };

  const rateBps = Number(cessRateBps ?? 0);
  const perUnit = Number(cessSpecificPaisePerUnit ?? 0);
  if (!Number.isFinite(taxablePaise) || taxablePaise < 0) return NIL;
  if (!Number.isFinite(rateBps) || rateBps < 0) return NIL;
  if (!Number.isFinite(perUnit) || perUnit < 0) return NIL;
  if (!Number.isFinite(quantity) || quantity < 0) return NIL;

  const adValorem = Number(
    floorDivBigInt(
      BigInt(Math.trunc(taxablePaise)) * BigInt(Math.trunc(rateBps)),
      BigInt(10000),
    ),
  );
  const specific = perUnit ? decimalTruncate(quantity, Math.trunc(perUnit)) : 0;
  return {
    cess_paise: adValorem + specific,
    ad_valorem_paise: adValorem,
    specific_paise: specific,
  };
}
