"use client";

import { useEffect, useRef, useState } from "react";
import { loadThree, canRunGlobe } from "./three-loader";
import { CITIES, ARCS, INDIA_CENTRE } from "./geography";
import { isLand } from "./landmask";
import {
  CORE_VERTEX,
  CORE_FRAGMENT,
  ATMOSPHERE_VERTEX,
  ATMOSPHERE_FRAGMENT,
  LAND_VERTEX,
  LAND_FRAGMENT,
  HUB_VERTEX,
  HUB_FRAGMENT,
  ARC_VERTEX,
  ARC_FRAGMENT,
} from "./globe-shaders";

/**
 * The hero globe.
 *
 * ── WHAT CHANGED ON 16 SEPTEMBER 2026, AND WHY ────────────────────────────
 * The owner compared the live hero against the brief's reference image: "I
 * dont think you have perfectly imported the image … you can clearly see the
 * difference." They were right, and the difference had a cause rather than
 * being a matter of taste.
 *
 * The reference is a dark EARTH — continents picked out in light, a luminous
 * blue atmosphere, thick glowing sweeps between cities. What shipped was a
 * WIREFRAME: a latitude/longitude graticule, 1,400 evenly scattered dots with
 * no relationship to any landmass, and one-pixel arcs. It was a sphere with a
 * grid on it, and no amount of colour tuning turns that into a planet.
 *
 * The reason is recorded in geography.ts, which rejected a coastline because it
 * "would have to be written from memory here". Sound reasoning, false premise:
 * Natural Earth's shoreline installs from npm. So ./landmask.ts now carries a
 * measured 0.5-degree land mask (generated by scripts/build-landmask.mjs from a
 * vendored copy, pinned by eleven coordinate checks in the backend suite), the
 * graticule is GONE, and the point field is land only.
 *
 * Four other things moved with it, each matching something in the reference the
 * old scene had no mechanism for — see globe-shaders.ts for the GLSL and why
 * each needs a shader rather than a stock material:
 *
 *   - limb darkening on every point, so a field of dots reads as a sphere;
 *   - a fresnel atmosphere shell, replacing a flat sprite that could not follow
 *     the silhouette;
 *   - arcs as glowing ribbons with a comet head and tail, replacing a 1px line
 *     plus a second Points object chasing a sampled position along it;
 *   - hubs that breathe, each on its own phase.
 *
 * ── EVERY PERFORMANCE GUARD IS KEPT, AND THEY ARE NOT OPTIONAL ────────────
 * Measured on the page this lineage replaces: with the globe running the hero
 * held 11-14fps, and blocking three.min.js restored it to 60. The brief then
 * asks for orbits, floating cards and parallax on top of that. So:
 *
 *   - the scene is capped to ~30fps (GLOBE_FRAME_MS). It is a slow continuous
 *     drift; 30 and 60 are indistinguishable and it halves the GPU cost.
 *   - it goes quiet for SCROLL_QUIET_MS after every scroll event, because the
 *     hero is the first screenful and therefore exactly where scrolling starts.
 *   - it stops entirely once the hero leaves the viewport, or the tab is hidden.
 *   - the render resolution is capped well below native device pixels: this is
 *     a soft glowy object, so a lower internal resolution is visually
 *     near-identical and dramatically cheaper on the fill-rate-bound integrated
 *     GPUs in ordinary laptops.
 *   - the scroll fade is plain CSS opacity and is applied BEFORE the skip
 *     guards, so the globe still dissolves smoothly during the very scroll in
 *     which its WebGL work is being skipped.
 *
 * The land field is ONE extra Points in the same draw-call budget the old point
 * cloud occupied, and the tube arcs replace the lines one for one — the arc
 * pulse actually removed an object. The cost that did grow is fill rate, which
 * is why the DPR cap and the frame cap above matter more than they did before
 * rather than less.
 *
 * `canRunGlobe()` decides whether any of this happens. When it says no —
 * reduced motion, a phone, <=4 GB of memory, no WebGL context — three.min.js is
 * never even downloaded and the static SVG below is the hero visual. It is
 * rendered either way and simply never covered, which is also what keeps the
 * hero from shifting while the scene loads.
 */

const GLOBE_FRAME_MS = 33;
const SCROLL_QUIET_MS = 150;
const PARTICLE_COUNT = 190;
const R = 1;

/**
 * How many candidate points are walked to build the land field.
 *
 * About 29% of the globe is land, so this yields roughly 26,000 points on the
 * continents. It is a startup cost only — a mask lookup per candidate, well
 * under a frame — and NOT a per-frame cost, which is the number that matters:
 * the draw is one Points object whatever the count.
 *
 * It was 47,000 candidates (~13,500 points) and the owner compared the result
 * against the reference again: "i want you to exactly copy the globe as it is
 * in the image". The reference reads as CITY LIGHTS — a fine, dense stipple —
 * and half this many dots at nearly twice this size reads as a dot matrix
 * instead. Density and dot size move together: more points only helps if each
 * one gets smaller, or the continents blur into a solid mass.
 */
const LAND_CANDIDATES = 90000;

/** Vertical field of view, degrees. The point shader needs it — see `projScale`. */
const FOV = 40;

/**
 * The X tilt that puts INDIA WHERE THE REFERENCE PUTS IT — above the centre of
 * the disc, not on it.
 *
 * This is measurable rather than a taste: in the reference image the globe's
 * centre and the subcontinent are about 45% of the radius apart, vertically,
 * and the white tick badge sits at the centre with India clear above it.
 *
 * Rotating the group about +X by `a` sends a surface point (0, y, z) to
 * y' = y·cos a − z·sin a. India is at latitude 22N facing the camera, so
 * (y, z) = (sin 22°, cos 22°) = (0.375, 0.927), and solving
 * 0.375·cos a − 0.927·sin a = 0.41 gives a ≈ −0.045. NEGATIVE — the previous
 * +0.28 tipped the north pole toward the viewer and pushed India DOWN to 10% of
 * the radius, which is why it landed under the badge.
 *
 * That is also the real fix for the badge. It was removed on 16-09-2026 for
 * covering the subcontinent; the reference has both, because it has them at
 * different heights. Moving the planet was the answer, not deleting the mark.
 */
const INDIA_TILT_X = -0.045;

/**
 * The diameter, in WORLD units, of an ordinary land dot.
 *
 * Point sizes are world-space and the shader converts them to pixels, rather
 * than being pixel figures scaled by something convenient. The first draft did
 * the convenient thing — `gl_PointSize = aSize * (canvasHeight * 0.55) / -z`
 * with `aSize` starting at 1 — which made every dot about 70 pixels across and
 * rendered the planet as one white disc. The arithmetic below is the real
 * projection and it is worth writing down rather than tuning by eye.
 *
 * At the hero's size this lands each dot a shade over one pixel, which is what
 * makes the field read as lights rather than as a grid of circles.
 */
const LAND_DOT_WORLD = 0.0088;
const HUB_DOT_WORLD = { major: 0.055, minor: 0.036 };

/** Geographic latitude/longitude to a point on a sphere of radius `r`. */
function latLonToVec3(lat: number, lon: number, r: number): [number, number, number] {
  const phi = ((90 - lat) * Math.PI) / 180;
  const theta = ((lon + 180) * Math.PI) / 180;
  return [
    -r * Math.sin(phi) * Math.cos(theta),
    r * Math.cos(phi),
    r * Math.sin(phi) * Math.sin(theta),
  ];
}

/**
 * The Y rotation that brings a given longitude round to face the camera (+Z).
 *
 * With the mapping above, a point at longitude L sits at (180 − (L + 180))
 * degrees measured from +X toward +Z, i.e. at −L. Rotating the group by `a`
 * about +Y moves a point at angle φ to φ − a, and the camera looks down −Z at
 * the +Z face (φ = 90°). So −L − a = 90, hence a = −(L + 90).
 */
function rotationFacing(lon: number): number {
  return (-(lon + 90) * Math.PI) / 180;
}

/** Angular distance in degrees between two lat/lon points. */
function angularDistanceDeg(aLat: number, aLon: number, bLat: number, bLon: number): number {
  const toRad = Math.PI / 180;
  const p1 = aLat * toRad;
  const p2 = bLat * toRad;
  const dl = (bLon - aLon) * toRad;
  const c = Math.sin(p1) * Math.sin(p2) + Math.cos(p1) * Math.cos(p2) * Math.cos(dl);
  return (Math.acos(Math.max(-1, Math.min(1, c))) * 180) / Math.PI;
}

/** Points along the great circle between two unit vectors, bulged outward. */
function arcPoints(
  a: [number, number, number],
  b: [number, number, number],
  segments: number,
  bulge: number
): [number, number, number][] {
  const dot = Math.max(-1, Math.min(1, a[0] * b[0] + a[1] * b[1] + a[2] * b[2]));
  const omega = Math.acos(dot);
  const sinO = Math.sin(omega);
  const out: [number, number, number][] = [];
  for (let i = 0; i <= segments; i++) {
    const t = i / segments;
    // Degenerate (coincident) endpoints would divide by zero; fall back to a
    // straight lerp, which for identical points is simply the point itself.
    let x: number, y: number, z: number;
    if (sinO < 1e-6) {
      x = a[0] + (b[0] - a[0]) * t;
      y = a[1] + (b[1] - a[1]) * t;
      z = a[2] + (b[2] - a[2]) * t;
    } else {
      const wa = Math.sin((1 - t) * omega) / sinO;
      const wb = Math.sin(t * omega) / sinO;
      x = a[0] * wa + b[0] * wb;
      y = a[1] * wa + b[1] * wb;
      z = a[2] * wa + b[2] * wb;
    }
    const lift = 1 + bulge * Math.sin(Math.PI * t);
    out.push([x * lift, y * lift, z * lift]);
  }
  return out;
}

/**
 * The land point field.
 *
 * A Fibonacci sphere walked point by point, keeping only what the mask calls
 * land. Fibonacci rather than a random lat/lon because random clusters hard at
 * the poles — which on this globe would be a bright Arctic and a sparse
 * equator, the opposite of what the picture wants.
 *
 * Colour is a function of distance from India and nothing else. The
 * subcontinent's own points are warm and bright, a wide falloff carries that
 * warmth across South and Central Asia, and the rest of the world sits in a
 * cool blue. That is the brief's "India visibly central" expressed as a
 * gradient rather than as a rotation nobody can see once the globe drifts.
 */
function buildLandField() {
  const pos: number[] = [];
  const col: number[] = [];
  const size: number[] = [];
  const golden = Math.PI * (3 - Math.sqrt(5));

  for (let i = 0; i < LAND_CANDIDATES; i++) {
    const y = 1 - (i / (LAND_CANDIDATES - 1)) * 2;
    const radius = Math.sqrt(Math.max(0, 1 - y * y));
    const theta = golden * i;
    const x = Math.cos(theta) * radius;
    const z = Math.sin(theta) * radius;

    // Inverse of latLonToVec3 for a unit vector, so the mask is asked about the
    // same coordinate the point will be drawn at.
    const lat = (Math.asin(Math.max(-1, Math.min(1, y))) * 180) / Math.PI;
    const lon = ((Math.atan2(z, -x) * 180) / Math.PI) - 180;
    if (!isLand(lat, lon)) continue;

    pos.push(x * R * 1.003, y * R * 1.003, z * R * 1.003);

    const d = angularDistanceDeg(lat, ((((lon % 360) + 540) % 360) - 180), INDIA_CENTRE.lat, INDIA_CENTRE.lon);
    const home = Math.max(0, 1 - d / 26); // the subcontinent itself
    const region = Math.max(0, 1 - d / 70); // and its neighbourhood, softly
    // A cool white-cyan that goes to near-white over India. The previous values
    // started at (0.34, 0.46, 0.74) — a mid blue-grey, which against a navy
    // sphere gave the continents almost no separation from the ocean. The
    // reference picks them out in light, so the contrast has to come from BOTH
    // ends: these lift, and the core below drops to near-black.
    col.push(
      0.62 + region * 0.18 + home * 0.2,
      0.79 + region * 0.13 + home * 0.21,
      0.97 + region * 0.03 + home * 0.03
    );
    // WORLD units, not a multiplier — see PROJECTED_PX for why the shader needs
    // a real size rather than an arbitrary one scaled by the canvas height.
    size.push(LAND_DOT_WORLD * (1 + home * 1.3 + region * 0.22));
  }

  return {
    position: new Float32Array(pos),
    color: new Float32Array(col),
    size: new Float32Array(size),
    count: size.length,
  };
}

export function HeroGlobe({ className = "" }: { className?: string }) {
  const stageRef = useRef<HTMLDivElement | null>(null);
  const fadeRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [live, setLive] = useState(false);

  // The scroll-driven dissolve. Runs in BOTH modes — the static SVG has to fade
  // out over the section boundary just as the canvas does, or the fallback
  // visitor gets a globe sitting on top of the next section.
  useEffect(() => {
    const stage = stageRef.current;
    const fade = fadeRef.current;
    if (!stage || !fade) return;
    let raf = 0;
    const apply = () => {
      raf = 0;
      const rect = stage.getBoundingClientRect();
      if (!rect.height) return;
      const p = Math.min(1, Math.max(0, -rect.top / (rect.height * 0.9)));
      fade.style.opacity = (1 - Math.max(0, (p - 0.55) / 0.45)).toFixed(2);
    };
    const onScroll = () => {
      if (!raf) raf = requestAnimationFrame(apply);
    };
    apply();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      cancelAnimationFrame(raf);
    };
  }, []);

  useEffect(() => {
    if (!canRunGlobe()) return;

    let disposed = false;
    let raf = 0;
    let renderer: any = null;
    const disposables: any[] = [];

    loadThree()
      .then((THREE) => {
        const canvas = canvasRef.current;
        const stage = stageRef.current;
        if (disposed || !canvas || !stage) return;

        const RENDER_DPR = Math.min(window.devicePixelRatio || 1, 1.25);
        let w = stage.clientWidth || 600;
        let h = stage.clientHeight || 600;

        renderer = new THREE.WebGLRenderer({ canvas, alpha: true, antialias: true });
        renderer.setPixelRatio(RENDER_DPR);
        renderer.setSize(w, h, false);

        const scene = new THREE.Scene();
        const camera = new THREE.PerspectiveCamera(FOV, w / h, 0.1, 100);
        camera.position.set(0, 0, 5.05);

        // Two nested groups so the India-facing spin (Y) is applied before the
        // viewing tilt (X). A single Euler would compose them in whichever order
        // the rotation order happens to be, which is exactly the kind of thing
        // that silently puts the Pacific in the middle.
        const tilt = new THREE.Group();
        tilt.rotation.x = INDIA_TILT_X;
        const spin = new THREE.Group();
        const baseY = rotationFacing(INDIA_CENTRE.lon);
        spin.rotation.y = baseY;
        tilt.add(spin);
        scene.add(tilt);

        /**
         * World size to pixels, for a perspective camera.
         *
         * A sphere of diameter `s` at view depth `d` spans a fraction
         * `s / (2 d tan(fov/2))` of the viewport's HEIGHT, so in device pixels
         * it is `s * H / (2 tan(fov/2)) / d`. Everything but `d` is constant
         * per frame, which is this number; the shader divides by `-mv.z`.
         *
         * Recomputed on resize, so a dot is the same physical size whatever the
         * hero's height — and it is derived rather than tuned, because a
         * hand-picked constant is what drew the planet as a white disc the
         * first time.
         */
        const projScale = () =>
          (h * RENDER_DPR) / (2 * Math.tan(((FOV / 2) * Math.PI) / 180));

        // ── The planet ────────────────────────────────────────────────────
        const coreGeo = new THREE.SphereGeometry(R * 0.994, 64, 48);
        const coreMat = new THREE.ShaderMaterial({
          vertexShader: CORE_VERTEX,
          fragmentShader: CORE_FRAGMENT,
          uniforms: {
            // NEAR-BLACK, not navy. Contrast is what makes a lit coastline
            // read, and it is made at both ends: the dots lift toward white and
            // the ocean drops away under them. At 0x10203f the continents and
            // the sea were close enough in value that the land read as texture
            // rather than as light.
            uCentre: { value: new THREE.Color(0x071223) },
            uLimb: { value: new THREE.Color(0x01040c) },
          },
        });
        spin.add(new THREE.Mesh(coreGeo, coreMat));
        disposables.push(coreGeo, coreMat);

        // ── Continents ────────────────────────────────────────────────────
        const field = buildLandField();
        const landGeo = new THREE.BufferGeometry();
        landGeo.setAttribute("position", new THREE.BufferAttribute(field.position, 3));
        landGeo.setAttribute("aColor", new THREE.BufferAttribute(field.color, 3));
        landGeo.setAttribute("aSize", new THREE.BufferAttribute(field.size, 1));
        const landMat = new THREE.ShaderMaterial({
          vertexShader: LAND_VERTEX,
          fragmentShader: LAND_FRAGMENT,
          uniforms: { uScale: { value: projScale() } },
          transparent: true,
          depthWrite: false,
          // NOT additive. The land field is the planet's lit SURFACE, and the
          // dots overlap where the projection foreshortens them — summing them
          // saturates the continents to white before the atmosphere is even
          // drawn. The hubs and arcs above the surface are additive, because
          // those genuinely are light sources.
        });
        spin.add(new THREE.Points(landGeo, landMat));
        disposables.push(landGeo, landMat);

        // ── City hubs ─────────────────────────────────────────────────────
        const hubVecs = CITIES.map((c) => latLonToVec3(c.lat, c.lon, R * 1.012));
        const hubPos = new Float32Array(CITIES.length * 3);
        const hubSize = new Float32Array(CITIES.length);
        const hubPhase = new Float32Array(CITIES.length);
        CITIES.forEach((c, i) => {
          hubPos[i * 3] = hubVecs[i][0];
          hubPos[i * 3 + 1] = hubVecs[i][1];
          hubPos[i * 3 + 2] = hubVecs[i][2];
          hubSize[i] = c.major ? HUB_DOT_WORLD.major : HUB_DOT_WORLD.minor;
          // Deterministic, not Math.random(): the hero is the first thing on the
          // page and a scene that differs between two loads is a scene nobody
          // can compare a screenshot of.
          hubPhase[i] = (i * 0.37) % 1;
        });
        const hubGeo = new THREE.BufferGeometry();
        hubGeo.setAttribute("position", new THREE.BufferAttribute(hubPos, 3));
        hubGeo.setAttribute("aSize", new THREE.BufferAttribute(hubSize, 1));
        hubGeo.setAttribute("aPhase", new THREE.BufferAttribute(hubPhase, 1));
        const hubMat = new THREE.ShaderMaterial({
          vertexShader: HUB_VERTEX,
          fragmentShader: HUB_FRAGMENT,
          uniforms: {
            uScale: { value: projScale() },
            uTime: { value: 0 },
            uCore: { value: new THREE.Color(0xffffff) },
            uHalo: { value: new THREE.Color(0x8fb6ff) },
          },
          transparent: true,
          depthWrite: false,
          blending: THREE.AdditiveBlending,
        });
        spin.add(new THREE.Points(hubGeo, hubMat));
        disposables.push(hubGeo, hubMat);

        // ── Network arcs ──────────────────────────────────────────────────
        // A tube rather than a line: the reference's sweeps have width and a
        // gradient, and a LineBasicMaterial has neither. 48 segments along and 5
        // around is the coarsest that still reads as round at this scale.
        //
        // THIN, AND THEY HUG THE SURFACE. Every city in geography.ts is in
        // India, so twelve arcs between them all bunch into the same few
        // degrees of the globe — at 0.0055 with a 0.17 bulge that bunching was
        // a bright tangle sitting on the subcontinent, which is the one part of
        // the picture that has to stay legible. Halving the width and the bulge
        // makes them the fine tracery the reference has; the travelling spark
        // stays bright, so the movement is not lost with the bulk.
        const arcMats: any[] = [];
        ARCS.forEach(([ai, bi], i) => {
          const pts = arcPoints(hubVecs[ai], hubVecs[bi], 48, 0.1).map(
            ([x, y, z]) => new THREE.Vector3(x, y, z)
          );
          const curve = new THREE.CatmullRomCurve3(pts);
          const g = new THREE.TubeGeometry(curve, 64, 0.0032, 5, false);
          const m = new THREE.ShaderMaterial({
            vertexShader: ARC_VERTEX,
            fragmentShader: ARC_FRAGMENT,
            uniforms: {
              uColor: { value: new THREE.Color(0x76a8f2) },
              uSpark: { value: new THREE.Color(0xffffff) },
              uTime: { value: 0 },
              uPhase: { value: (i / ARCS.length) % 1 },
              uSpeed: { value: 0.16 },
              uBase: { value: 0.3 },
            },
            transparent: true,
            depthWrite: false,
            blending: THREE.AdditiveBlending,
          });
          spin.add(new THREE.Mesh(g, m));
          arcMats.push(m);
          disposables.push(g, m);
        });

        // ── Atmosphere ────────────────────────────────────────────────────
        const atmGeo = new THREE.SphereGeometry(R * 1.085, 48, 36);
        const atmMat = new THREE.ShaderMaterial({
          vertexShader: ATMOSPHERE_VERTEX,
          fragmentShader: ATMOSPHERE_FRAGMENT,
          uniforms: {
            uColor: { value: new THREE.Color(0x74b4f5) },
            // A HIGH power is what keeps this a rim. The fresnel term falls off
            // as pow(1 - facing, uPower), so a low exponent spreads it inward
            // across the whole disc — at 3.0 on a 1.19R shell it read as a fat
            // blue band wrapped round the planet rather than as air above it.
            // Tighter shell, steeper falloff.
            uPower: { value: 4.6 },
            // 1.15 blew the silhouette to white and 0.5 was too timid against
            // the darker planet below. The rim has to be clearly there —
            // the reference's is — without becoming the brightest thing in the
            // frame, which is the continents.
            uIntensity: { value: 0.82 },
          },
          side: THREE.BackSide,
          transparent: true,
          depthWrite: false,
          blending: THREE.AdditiveBlending,
        });
        tilt.add(new THREE.Mesh(atmGeo, atmMat));
        disposables.push(atmGeo, atmMat);

        // A soft bloom behind the whole thing, which the fresnel shell cannot
        // give on its own — the shell stops at its own radius, and the reference
        // image's halo reaches well past the silhouette.
        const glowCanvas = document.createElement("canvas");
        glowCanvas.width = glowCanvas.height = 128;
        const gctx = glowCanvas.getContext("2d");
        if (gctx) {
          const grad = gctx.createRadialGradient(64, 64, 0, 64, 64, 64);
          // The centre stop is nearly clear on purpose: this sprite sits
          // BEHIND the planet and is meant to be a halo escaping past the
          // silhouette, not a wash over the face of it.
          grad.addColorStop(0, "rgba(96,150,240,0.22)");
          grad.addColorStop(0.5, "rgba(88,132,228,0.08)");
          grad.addColorStop(1, "rgba(80,116,220,0)");
          gctx.fillStyle = grad;
          gctx.fillRect(0, 0, 128, 128);
        }
        const glowTex = new THREE.CanvasTexture(glowCanvas);
        const glowMat = new THREE.SpriteMaterial({
          map: glowTex,
          transparent: true,
          blending: THREE.AdditiveBlending,
          depthWrite: false,
        });
        const glowSprite = new THREE.Sprite(glowMat);
        glowSprite.scale.set(3.1, 3.1, 1);
        glowSprite.position.z = -1.4; // behind the planet, so it haloes rather than washes
        tilt.add(glowSprite);
        disposables.push(glowTex, glowMat);

        // ── Orbital sweeps ────────────────────────────────────────────────
        // FOUR, thin and bright. There were two heavy ones, on the reasoning
        // that "three thin ones read as a diagram"; holding the render beside
        // the reference shows that to be wrong about this picture. It has four
        // or five fine bright arcs at clearly different inclinations, crossing
        // in front of the planet and behind it, and the count is what makes it
        // read as an orbital system rather than as a ringed planet.
        //
        // Thin AND bright, not thick and dim: a 1px line at high opacity reads
        // as a drawn arc, which is what the reference has. Below about 0.004
        // world units they alias into dashes at this size, so that is the floor.
        const rings: any[] = [];
        [
          { r: 1.22, tube: 0.0045, rx: 0.34, ry: 0, rz: 0.12, opacity: 0.72, speed: 0.0020 },
          { r: 1.42, tube: 0.0042, rx: 1.24, ry: 0.42, rz: 0, opacity: 0.5, speed: -0.0015 },
          { r: 1.63, tube: 0.004, rx: -0.42, ry: 0.22, rz: 0.92, opacity: 0.42, speed: 0.0012 },
          { r: 1.86, tube: 0.004, rx: 1.46, ry: -0.3, rz: 0.4, opacity: 0.3, speed: -0.0009 },
        ].forEach((def) => {
          const g = new THREE.TorusGeometry(def.r, def.tube, 8, 128);
          const m = new THREE.MeshBasicMaterial({
            color: 0x8dc0f8,
            transparent: true,
            opacity: def.opacity,
            blending: THREE.AdditiveBlending,
            depthWrite: false,
          });
          const ring = new THREE.Mesh(g, m);
          ring.rotation.set(def.rx, def.ry, def.rz);
          ring.userData.speed = def.speed;
          tilt.add(ring);
          rings.push(ring);
          disposables.push(g, m);
        });

        // ── Inward-drifting particles ─────────────────────────────────────
        const resetParticle = (arr: Float32Array, i: number) => {
          const r = 1.55 + Math.random() * 1.3;
          const theta = Math.random() * Math.PI * 2;
          const phi = Math.acos(Math.random() * 2 - 1);
          arr[i * 3] = r * Math.sin(phi) * Math.cos(theta);
          arr[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta);
          arr[i * 3 + 2] = r * Math.cos(phi);
        };
        const partPos = new Float32Array(PARTICLE_COUNT * 3);
        for (let i = 0; i < PARTICLE_COUNT; i++) resetParticle(partPos, i);
        const partGeo = new THREE.BufferGeometry();
        partGeo.setAttribute("position", new THREE.BufferAttribute(partPos, 3));
        const partMat = new THREE.PointsMaterial({
          color: 0x9cc6fa,
          size: 0.026,
          transparent: true,
          opacity: 0.8,
          sizeAttenuation: true,
          blending: THREE.AdditiveBlending,
          depthWrite: false,
        });
        tilt.add(new THREE.Points(partGeo, partMat));
        disposables.push(partGeo, partMat);

        // ── Loop ──────────────────────────────────────────────────────────
        let lastDraw = 0;
        let quietUntil = 0;
        let t = 0;
        const onScroll = () => {
          quietUntil = performance.now() + SCROLL_QUIET_MS;
        };
        window.addEventListener("scroll", onScroll, { passive: true });

        const frame = (ts?: number) => {
          raf = requestAnimationFrame(frame);
          if (disposed) return;
          try {
            const rect = stage.getBoundingClientRect();
            if (document.hidden || rect.bottom <= 0) return;

            // Camera dolly tracks scroll every frame even when the draw is
            // skipped — it costs nothing and simply takes effect on the next
            // real draw.
            const p = Math.min(1, Math.max(0, -rect.top / (rect.height * 0.9)));
            camera.position.z = 5.05 - p * 1.5;

            if (quietUntil && (ts || 0) < quietUntil) return;
            if (ts && ts - lastDraw < GLOBE_FRAME_MS) return;
            lastDraw = ts || 0;

            const cw = stage.clientWidth;
            const ch = stage.clientHeight;
            if (cw && ch && (cw !== w || ch !== h)) {
              w = cw;
              h = ch;
              camera.aspect = w / h;
              camera.updateProjectionMatrix();
              renderer.setSize(w, h, false);
              landMat.uniforms.uScale.value = projScale();
              hubMat.uniforms.uScale.value = projScale();
            }

            t += 1;
            // Seconds, so the shader speeds read as "per second" rather than as
            // "per drawn frame" — which would run at a different rate the moment
            // the frame cap or the scroll-quiet window skipped a draw.
            const time = t * (GLOBE_FRAME_MS / 1000);
            hubMat.uniforms.uTime.value = time;
            for (const m of arcMats) m.uniforms.uTime.value = time;

            // THE EARTH ITSELF IS LOCKED, and that is the owner's call:
            // "even if the globe is not moving its fine but i want you to
            // exactly copy the globe as it is in the image". It used to
            // oscillate +/- 15 degrees in Y and +/- 3 in X, which is the one
            // thing that cannot be reconciled with copying a still frame —
            // for most of every cycle the planet is NOT in the reference's
            // pose, and India drifts out from under the composition built
            // around it.
            //
            // The scene is still alive: the orbital sweeps turn, the arc
            // pulses run, the hubs breathe and the particles fall inward.
            // Only the globe holds its mark.

            rings.forEach((ring) => {
              ring.rotation.z += ring.userData.speed;
            });

            const posAttr = partGeo.attributes.position;
            const arr = posAttr.array as Float32Array;
            for (let i = 0; i < PARTICLE_COUNT; i++) {
              const ix = i * 3;
              let x = arr[ix];
              let y = arr[ix + 1];
              let z = arr[ix + 2];
              const len = Math.sqrt(x * x + y * y + z * z) || 1;
              const speed = 0.007;
              x -= (x / len) * speed;
              y -= (y / len) * speed;
              z -= (z / len) * speed;
              if (len < 1.2) resetParticle(arr, i);
              else {
                arr[ix] = x;
                arr[ix + 1] = y;
                arr[ix + 2] = z;
              }
            }
            posAttr.needsUpdate = true;

            camera.lookAt(0, 0, 0);
            renderer.render(scene, camera);
          } catch {
            /* a lost context must not take the page down with it */
          }
        };

        setLive(true);
        raf = requestAnimationFrame(frame);

        // Captured for the cleanup closure below.
        (renderer as any).__psCleanup = () => {
          window.removeEventListener("scroll", onScroll);
        };
      })
      .catch(() => {
        /* the static globe is already on screen; nothing to do */
      });

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      if (renderer) {
        try {
          (renderer as any).__psCleanup?.();
          disposables.forEach((d) => d?.dispose?.());
          renderer.dispose();
        } catch {
          /* disposal is best-effort */
        }
      }
    };
  }, []);

  return (
    <div ref={stageRef} className={`relative ${className}`} aria-hidden="true">
      <div ref={fadeRef} className="absolute inset-0">
        <StaticGlobe
          className="absolute inset-0 h-full w-full transition-opacity duration-700"
          style={{ opacity: live ? 0 : 1 }}
        />
        <canvas
          ref={canvasRef}
          className="absolute inset-0 h-full w-full transition-opacity duration-700"
          style={{ opacity: live ? 1 : 0 }}
        />
      </div>
    </div>
  );
}

/**
 * The globe as a static SVG.
 *
 * NOT A PLACEHOLDER. For a visitor on reduced motion, on a phone, on a
 * low-memory machine or in a browser with no WebGL, this IS the hero visual —
 * and `canRunGlobe()` says no to every phone, so on mobile it is what EVERYONE
 * sees. It is also what reserves the hero's box while three.min.js downloads,
 * which keeps the headline from jumping (brief §15).
 *
 * SO IT GETS THE CONTINENTS TOO. It used to be a wireframe of ellipses, and
 * leaving it that way while the WebGL scene grew a coastline would mean the
 * majority of visitors never saw the thing the owner asked for. Same mask, same
 * India-facing pose, orthographically projected, sampled at a 1.7-degree step
 * because this is inline markup in the HTML payload rather than a buffer — a
 * few thousand visible dots, which gzips to almost nothing.
 *
 * The dot RADIUS and opacity fall off toward the limb for the same reason the
 * shader darkens there: it is what stops a field of dots reading as a disc.
 */
function StaticGlobe({ className = "", style }: { className?: string; style?: React.CSSProperties }) {
  const a = rotationFacing(INDIA_CENTRE.lon);
  const tiltA = INDIA_TILT_X;
  const cosA = Math.cos(a);
  const sinA = Math.sin(a);
  const cosT = Math.cos(tiltA);
  const sinT = Math.sin(tiltA);

  /** Rotate into the scene's pose and project orthographically onto the face. */
  const project = (lat: number, lon: number) => {
    const [x, y, z] = latLonToVec3(lat, lon, 1);
    const rx = x * cosA + z * sinA;
    const rz = -x * sinA + z * cosA;
    const ty = y * cosT - rz * sinT;
    const tz = y * sinT + rz * cosT;
    return { x: 100 + rx * 78, y: 100 - ty * 78, front: tz > 0, facing: tz };
  };

  // Three depth BANDS rather than a per-dot radius and opacity. Each dot is
  // then two attributes instead of four, and this markup is inlined in the
  // page's own HTML — at ~1,500 dots that difference is around 35 KB of the
  // document, for a gradient no eye can resolve at three steps or at thirty.
  const BANDS = [
    { min: 0.06, max: 0.33, r: 0.38, opacity: 0.4 },
    { min: 0.33, max: 0.66, r: 0.5, opacity: 0.68 },
    { min: 0.66, max: 1.01, r: 0.62, opacity: 0.95 },
  ];
  const bands: { x: string; y: string }[][] = BANDS.map(() => []);

  for (let lat = -84; lat <= 84; lat += 1.7) {
    // Constant spacing ON THE GROUND rather than in degrees: a fixed longitude
    // step piles points up at the poles, which on this projection is a bright
    // smear at the top and bottom of the disc.
    const step = 1.7 / Math.max(0.16, Math.cos((lat * Math.PI) / 180));
    for (let lon = -180; lon < 180; lon += step) {
      if (!isLand(lat, lon)) continue;
      const p = project(lat, lon);
      if (!p.front || p.facing < BANDS[0].min) continue;
      const band = BANDS.findIndex((b) => p.facing >= b.min && p.facing < b.max);
      if (band < 0) continue;
      bands[band].push({ x: p.x.toFixed(1), y: p.y.toFixed(1) });
    }
  }

  const hubs = CITIES.map((c) => ({ ...project(c.lat, c.lon), major: c.major })).filter(
    (d) => d.front
  );

  return (
    <svg viewBox="0 0 200 200" className={className} style={style} aria-hidden="true">
      <defs>
        <radialGradient id="ps-globe-atm" cx="50%" cy="50%" r="50%">
          <stop offset="55%" stopColor="#74b4f5" stopOpacity="0" />
          <stop offset="80%" stopColor="#74b4f5" stopOpacity="0.42" />
          <stop offset="100%" stopColor="#74b4f5" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="ps-globe-face" cx="42%" cy="36%" r="76%">
          <stop offset="0%" stopColor="#0a1628" />
          <stop offset="100%" stopColor="#01040c" />
        </radialGradient>
      </defs>

      <circle cx="100" cy="100" r="97" fill="url(#ps-globe-atm)" />
      <circle cx="100" cy="100" r="78" fill="url(#ps-globe-face)" />

      {BANDS.map((b, bi) => (
        <g key={bi} fill="#b6d8fb" opacity={b.opacity}>
          {bands[bi].map((d, i) => (
            <circle key={i} cx={d.x} cy={d.y} r={b.r} />
          ))}
        </g>
      ))}

      <g>
        {hubs.map((d, i) => (
          <circle
            key={i}
            cx={d.x.toFixed(1)}
            cy={d.y.toFixed(1)}
            r={d.major ? 1.7 : 1.1}
            fill="#e8f0ff"
            opacity={(0.45 + d.facing * 0.5).toFixed(2)}
          />
        ))}
      </g>

      <g stroke="#8dc0f8" fill="none" strokeWidth="0.5">
        <ellipse cx="100" cy="100" rx="95" ry="30" strokeOpacity="0.62" transform="rotate(-16 100 100)" />
        <ellipse cx="100" cy="100" rx="90" ry="48" strokeOpacity="0.4" transform="rotate(26 100 100)" />
        <ellipse cx="100" cy="100" rx="84" ry="64" strokeOpacity="0.26" transform="rotate(-52 100 100)" />
      </g>
      <circle cx="100" cy="100" r="78" fill="none" stroke="#9ecbfb" strokeOpacity="0.4" strokeWidth="0.7" />
    </svg>
  );
}
