"""
E-Invoice Integration Layer — Provider abstraction for IRP (Invoice Registration Portal).
CGST Act Section 31B — E-Invoice mandate for eligible taxpayers.

# CA REVIEW REQUIRED — DO NOT AUTO-SUBMIT to IRP/government portal
All IRN generation and cancellation requires explicit CA action.
"""
from __future__ import annotations

import logging
import os
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from uuid import uuid4

_logger = logging.getLogger("caflow.einvoice")
_USE_MOCK = not os.environ.get("SUPABASE_URL")

_MOCK_RECORDS: dict[str, dict] = {}


# ── Provider Abstraction ──────────────────────────────────────────────────────

class EInvoiceProvider(ABC):
    """Abstract interface for e-invoice integration providers."""

    @abstractmethod
    def generate_irn(self, invoice_data: dict) -> dict:
        """Generate Invoice Reference Number. Returns {irn, ack_number, ack_date, qr_data}."""
        ...

    @abstractmethod
    def cancel_irn(self, irn: str, reason_code: int, reason: str) -> dict:
        """Cancel an existing IRN. Returns {status, cancelled_at}."""
        ...

    @abstractmethod
    def get_invoice_status(self, irn: str) -> dict:
        """Get current status of an IRN. Returns {status, details}."""
        ...


class ManualProvider(EInvoiceProvider):
    """Manual provider — CA generates IRN on government portal and records here."""

    def generate_irn(self, invoice_data: dict) -> dict:
        return {"irn": None, "ack_number": None, "ack_date": None, "qr_data": None}

    def cancel_irn(self, irn: str, reason_code: int, reason: str) -> dict:
        return {"status": "cancelled", "cancelled_at": datetime.now(timezone.utc).isoformat()}

    def get_invoice_status(self, irn: str) -> dict:
        return {"status": "unknown", "details": {}}


def get_provider(provider_name: str = "manual") -> EInvoiceProvider:
    if provider_name == "manual":
        return ManualProvider()
    # Future: ClearTax, Tally, e-Invoice6 etc.
    _logger.warning("Unknown e-invoice provider '%s', falling back to manual", provider_name)
    return ManualProvider()


# ── Service Functions ─────────────────────────────────────────────────────────

def _supabase():
    from core.supabase_client import get_supabase
    return get_supabase()


def create_einvoice_record(
    firm_id: str,
    client_id: str,
    invoice_number: str,
    invoice_date: str,
    created_by: str,
    sales_invoice_id: str | None = None,
    provider: str = "manual",
) -> dict:
    """Create e-invoice record in draft state."""
    if _USE_MOCK:
        row = {
            "id": str(uuid4()),
            "firm_id": firm_id,
            "client_id": client_id,
            "sales_invoice_id": sales_invoice_id,
            "invoice_number": invoice_number,
            "invoice_date": invoice_date,
            "irn": None,
            "ack_number": None,
            "ack_date": None,
            "qr_data": None,
            "status": "draft",
            "provider": provider,
            "provider_response": {},
            "ca_review_required": True,
            "created_by": created_by,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        _MOCK_RECORDS[row["id"]] = row
        return row

    sb = _supabase()
    row = {
        "firm_id": firm_id,
        "client_id": client_id,
        "sales_invoice_id": sales_invoice_id,
        "invoice_number": invoice_number,
        "invoice_date": invoice_date,
        "status": "draft",
        "provider": provider,
        "ca_review_required": True,
        "created_by": created_by,
    }
    res = sb.table("einvoice_records").insert(row).execute()
    return res.data[0] if res.data else row


def record_irn_generated(
    firm_id: str,
    record_id: str,
    irn: str,
    ack_number: str,
    ack_date: str,
    qr_data: str | None = None,
    provider_response: dict | None = None,
) -> dict:
    """
    Record that CA has generated IRN on the government portal.
    # CA REVIEW REQUIRED — IRN must be generated by CA on IRP portal, not auto-submitted
    """
    update = {
        "irn": irn,
        "ack_number": ack_number,
        "ack_date": ack_date,
        "qr_data": qr_data,
        "status": "generated",
        "provider_response": provider_response or {},
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    if _USE_MOCK:
        if record_id in _MOCK_RECORDS:
            _MOCK_RECORDS[record_id].update(update)
        return _MOCK_RECORDS.get(record_id, {})

    sb = _supabase()
    res = sb.table("einvoice_records").update(update).eq("id", record_id).eq(
        "firm_id", firm_id
    ).execute()
    return res.data[0] if res.data else {}


def record_irn_cancelled(
    firm_id: str,
    record_id: str,
    cancellation_reason: str,
) -> dict:
    """
    Record IRN cancellation.
    # CA REVIEW REQUIRED — Cancellation must be done by CA on IRP portal
    """
    update = {
        "status": "cancelled",
        "cancellation_reason": cancellation_reason,
        "cancelled_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    if _USE_MOCK:
        if record_id in _MOCK_RECORDS:
            _MOCK_RECORDS[record_id].update(update)
        return _MOCK_RECORDS.get(record_id, {})

    sb = _supabase()
    res = sb.table("einvoice_records").update(update).eq("id", record_id).eq(
        "firm_id", firm_id
    ).execute()
    return res.data[0] if res.data else {}


def list_einvoices(
    firm_id: str,
    client_id: str,
    status: str | None = None,
) -> list[dict]:
    if _USE_MOCK:
        records = [r for r in _MOCK_RECORDS.values()
                   if r["firm_id"] == firm_id and r["client_id"] == client_id]
        if status:
            records = [r for r in records if r["status"] == status]
        return records

    sb = _supabase()
    q = sb.table("einvoice_records").select("*").eq("firm_id", firm_id).eq("client_id", client_id)
    if status:
        q = q.eq("status", status)
    res = q.order("created_at", desc=True).execute()
    return res.data or []
