"""
E-Way Bill Integration Layer — CGST Act Section 68, Rule 138.
E-Way Bill required for goods movement exceeding ₹50,000 in value.

# CA REVIEW REQUIRED — DO NOT AUTO-SUBMIT to NIC/GST portal
"""
from __future__ import annotations

import logging
import os
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from uuid import uuid4

_logger = logging.getLogger("caflow.eway_bill")
_USE_MOCK = not os.environ.get("SUPABASE_URL")

_MOCK_RECORDS: dict[str, dict] = {}


class EWayBillProvider(ABC):
    @abstractmethod
    def generate(self, data: dict) -> dict: ...

    @abstractmethod
    def extend_validity(self, ewb_number: str, data: dict) -> dict: ...

    @abstractmethod
    def cancel(self, ewb_number: str, reason: str) -> dict: ...

    @abstractmethod
    def get_status(self, ewb_number: str) -> dict: ...


class ManualEWayProvider(EWayBillProvider):
    """CA generates on government portal and records here."""

    def generate(self, data: dict) -> dict:
        return {"ewb_number": None, "ewb_date": None, "ewb_valid_upto": None}

    def extend_validity(self, ewb_number: str, data: dict) -> dict:
        return {"ewb_valid_upto": None}

    def cancel(self, ewb_number: str, reason: str) -> dict:
        return {"status": "cancelled"}

    def get_status(self, ewb_number: str) -> dict:
        return {"status": "unknown"}


def _supabase():
    from core.supabase_client import get_supabase_client
    return get_supabase_client()


def create_eway_bill(
    firm_id: str,
    client_id: str,
    invoice_number: str,
    dispatch_from: str,
    ship_to: str,
    goods_description: str,
    taxable_value_paise: int,
    created_by: str,
    sales_invoice_id: str | None = None,
    hsn_code: str | None = None,
    vehicle_number: str | None = None,
    vehicle_type: str | None = None,
    transport_mode: str | None = None,
    distance_km: int | None = None,
    transporter_id: str | None = None,
    transporter_name: str | None = None,
    provider: str = "manual",
) -> dict:
    """Create E-Way Bill record in draft state."""
    if _USE_MOCK:
        row = {
            "id": str(uuid4()),
            "firm_id": firm_id,
            "client_id": client_id,
            "sales_invoice_id": sales_invoice_id,
            "invoice_number": invoice_number,
            "ewb_number": None,
            "ewb_date": None,
            "ewb_valid_upto": None,
            "vehicle_number": vehicle_number,
            "vehicle_type": vehicle_type,
            "transport_mode": transport_mode,
            "distance_km": distance_km,
            "transporter_id": transporter_id,
            "transporter_name": transporter_name,
            "dispatch_from": dispatch_from,
            "ship_to": ship_to,
            "hsn_code": hsn_code,
            "goods_description": goods_description,
            "taxable_value_paise": taxable_value_paise,
            "status": "draft",
            "provider": provider,
            "ca_review_required": True,
            "created_by": created_by,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        _MOCK_RECORDS[row["id"]] = row
        return row

    sb = _supabase()
    row = {
        "firm_id": firm_id,
        "client_id": client_id,
        "sales_invoice_id": sales_invoice_id,
        "invoice_number": invoice_number,
        "vehicle_number": vehicle_number,
        "vehicle_type": vehicle_type,
        "transport_mode": transport_mode,
        "distance_km": distance_km,
        "transporter_id": transporter_id,
        "transporter_name": transporter_name,
        "dispatch_from": dispatch_from,
        "ship_to": ship_to,
        "hsn_code": hsn_code,
        "goods_description": goods_description,
        "taxable_value_paise": taxable_value_paise,
        "status": "draft",
        "provider": provider,
        "ca_review_required": True,
        "created_by": created_by,
    }
    res = sb.table("eway_bill_records").insert(row).execute()
    return res.data[0] if res.data else row


def record_ewb_generated(
    firm_id: str,
    record_id: str,
    ewb_number: str,
    ewb_date: str,
    ewb_valid_upto: str,
    provider_response: dict | None = None,
) -> dict:
    """
    Record E-Way Bill generated by CA on government portal.
    # CA REVIEW REQUIRED — EWB must be generated by CA on NIC portal
    """
    update = {
        "ewb_number": ewb_number,
        "ewb_date": ewb_date,
        "ewb_valid_upto": ewb_valid_upto,
        "status": "generated",
        "provider_response": provider_response or {},
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    if _USE_MOCK:
        if record_id in _MOCK_RECORDS:
            _MOCK_RECORDS[record_id].update(update)
        return _MOCK_RECORDS.get(record_id, {})

    sb = _supabase()
    res = sb.table("eway_bill_records").update(update).eq("id", record_id).eq(
        "firm_id", firm_id
    ).execute()
    return res.data[0] if res.data else {}


def record_ewb_extended(
    firm_id: str,
    record_id: str,
    new_valid_upto: str,
    extension_reason: str,
) -> dict:
    update = {
        "ewb_valid_upto": new_valid_upto,
        "extension_reason": extension_reason,
        "status": "extended",
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    if _USE_MOCK:
        if record_id in _MOCK_RECORDS:
            _MOCK_RECORDS[record_id].update(update)
        return _MOCK_RECORDS.get(record_id, {})

    sb = _supabase()
    res = sb.table("eway_bill_records").update(update).eq("id", record_id).eq(
        "firm_id", firm_id
    ).execute()
    return res.data[0] if res.data else {}


def record_ewb_cancelled(
    firm_id: str,
    record_id: str,
    cancellation_reason: str,
) -> dict:
    update = {
        "status": "cancelled",
        "cancellation_reason": cancellation_reason,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    if _USE_MOCK:
        if record_id in _MOCK_RECORDS:
            _MOCK_RECORDS[record_id].update(update)
        return _MOCK_RECORDS.get(record_id, {})

    sb = _supabase()
    res = sb.table("eway_bill_records").update(update).eq("id", record_id).eq(
        "firm_id", firm_id
    ).execute()
    return res.data[0] if res.data else {}


def list_eway_bills(
    firm_id: str,
    client_id: str,
    status: str | None = None,
) -> list[dict]:
    if _USE_MOCK:
        records = [r for r in _MOCK_RECORDS.values()
                   if r["firm_id"] == firm_id and r["client_id"] == client_id]
        if status:
            records = [r for r in records if r["status"] == status]
        return records

    sb = _supabase()
    q = sb.table("eway_bill_records").select("*").eq("firm_id", firm_id).eq("client_id", client_id)
    if status:
        q = q.eq("status", status)
    res = q.order("created_at", desc=True).execute()
    return res.data or []
