"""UDIN — Unique Document Identification Number (ICAI).

A UDIN is the number ICAI issues to a member in practice when they sign a
document, so that anyone holding the document can verify on ICAI's portal that
the member really signed it. It exists because forged attestations carrying a
CA's name were, and are, a live problem.

THE ONE RULE THAT MATTERS HERE: A UDIN CANNOT BE GENERATED BY THIS SOFTWARE.

It is issued by ICAI's UDIN portal to the signing member, against their own
membership credentials. Anything this codebase produced that looked like a UDIN
would be a fabricated attestation reference on a document that asserts a CA
signed it — which is the exact harm the number was created to prevent. So this
module only VALIDATES the shape of a UDIN a CA has obtained and typed in, and
the format check is deliberately weak: it rejects what cannot be a UDIN, and
makes no claim that what it accepts is real. Only ICAI's portal can say that.

FORMAT (18 characters, since the move from the earlier 15-character number):

    YY MMMMMM AAAAAAAAAA

    YY          last two digits of the year the number was generated
    MMMMMM      the member's six-digit ICAI membership registration number
    AAAAAAAAAA  ten alphanumeric characters generated by the portal

e.g. 19304576AKTSBN1359 — year 19, membership 304576, then the portal's own
ten characters.
"""
from __future__ import annotations

import re

# 8 leading digits (YY + six-digit membership number), then ten alphanumeric
# characters from the portal. Anchored, because a UDIN embedded in a longer
# string is not a UDIN.
_UDIN_RE = re.compile(r"^\d{8}[A-Za-z0-9]{10}$")

UDIN_LENGTH = 18


def normalise_udin(value: str | None) -> str | None:
    """Strip surrounding whitespace and upper-case the portal's characters.

    Returns None for anything empty, so "no UDIN recorded" has one
    representation rather than three (None, "", "   ").
    """
    if value is None:
        return None
    cleaned = "".join(str(value).split()).upper()
    return cleaned or None


def is_valid_udin(value: str | None) -> bool:
    """True if `value` COULD be a UDIN. Never that it is one.

    Shape only. A number that passes here may still be unissued, revoked, or
    belong to a different document — only ICAI's portal can answer that, and
    nothing in this product should imply otherwise.
    """
    cleaned = normalise_udin(value)
    return bool(cleaned and _UDIN_RE.match(cleaned))


def membership_number(value: str | None) -> str | None:
    """The six-digit ICAI membership number embedded in a UDIN.

    Useful for showing a CA which member's number they have entered, so a
    transposed digit is visible before the pack is issued.
    """
    cleaned = normalise_udin(value)
    if not cleaned or not _UDIN_RE.match(cleaned):
        return None
    return cleaned[2:8]


def describe_udin_format() -> str:
    """One line a UI or an error can show, so a rejected entry says what was
    expected rather than only that it was wrong."""
    return (
        "A UDIN is 18 characters: two digits for the year, six for the ICAI "
        "membership number, then ten alphanumeric characters issued by the "
        "ICAI UDIN portal. It is generated on that portal by the signing "
        "member and cannot be produced here."
    )
