"""Page numbers on every document this product produces.

── THE DEFECT ───────────────────────────────────────────────────────────────
Measured 19 September 2026: `grep -c 'onPage\\|canvasmaker'` across all six PDF
services returned **zero**. Not one document numbered its pages.

That matters most on the documents that run to more than one: a customer
STATEMENT (a year of invoices), a year-end PACK (statements, notes,
adjustments and a history in one file), a forty-line INVOICE, a bank
RECONCILIATION. Each of them is printed, signed, photocopied and filed, and
"Page 3 of 7" is the only way a reader knows a page is missing from the set in
front of them. An auditor's working papers are numbered for exactly this
reason.

── HOW ──────────────────────────────────────────────────────────────────────
ReportLab cannot know the TOTAL page count while it is laying out page 1, so
"Page 3 of 7" needs two passes. `NumberedCanvas` is the standard shape: hold
each page's state instead of emitting it, and at `save()` replay them all now
that the count is known. It is the only way to get "of N" without building the
document twice.

── WHAT IT DELIBERATELY DOES NOT DO ─────────────────────────────────────────
**No ₹.** ReportLab's core fonts are WinAnsiEncoding and have no glyph for
U+20B9 — it renders as a black box, which shipped twice. This module is under
`services/*pdf*.py` precisely so
`tests/test_no_pdf_renders_the_rupee_sign.py`'s glob catches it.

**Nothing else in the margin.** No firm name, no logo, no "generated by". The
footer of a document the CLIENT issues to a stranger is exactly where a
practice's branding has leaked in before (CLAUDE.md records three such bugs),
so this puts one thing there and that thing is a number.
"""
from __future__ import annotations

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as _canvas

#: Where the number sits, measured from the page's bottom-right. Inside the
#: 18mm bottom margin every service already uses, so it never collides with
#: the flowables above it.
_FROM_RIGHT = 18 * mm
_FROM_BOTTOM = 10 * mm
_FONT = ("Helvetica", 7.5)


class NumberedCanvas(_canvas.Canvas):
    """A canvas that stamps "Page N of M" on every page.

    Pass it as `canvasmaker=` to `doc.build(...)`. It is a class rather than an
    `onPage` callback because the TOTAL is not known until the last page has
    been laid out — an `onPage` hook can say "Page 3" and cannot say "of 7",
    and "of 7" is the half that tells a reader a page is missing.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_states: list[dict] = []

    def showPage(self):  # noqa: N802 — reportlab's own spelling
        # Hold the page instead of emitting it. `_startPage` resets the state
        # for the next one, which is what the base class's `showPage` would
        # otherwise do on its way out.
        self._saved_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_states)
        for state in self._saved_states:
            self.__dict__.update(state)
            self._draw_number(total)
            super().showPage()
        super().save()

    def _draw_number(self, total: int) -> None:
        page_w = self._pagesize[0] if getattr(self, "_pagesize", None) else A4[0]
        self.setFont(*_FONT)
        self.setFillGray(0.45)
        self.drawRightString(page_w - _FROM_RIGHT, _FROM_BOTTOM,
                             f"Page {self._pageNumber} of {total}")


def numbered(doc, story, **kwargs):
    """`doc.build(story)` with the pages numbered.

    A thin wrapper so a service reads `numbered(doc, story)` rather than
    remembering the keyword — and so a reader grepping for `doc.build` in a PDF
    service finds nothing and comes here, which is the point of putting the
    rule in one place.
    """
    return doc.build(story, canvasmaker=NumberedCanvas, **kwargs)
